### ISSUE TITLE
List of pages to include

### ISSUE THREAD

**Issue by rongjie-alter** [liveahero-wiki/liveahero-wiki.github.io#1]
Add comments for pages to be added

**Comment by InqEretaH** [comment]
Sui, Mokdai, Ryekie, Crowne, Huckle, Rakta, Loren, Narihito, Goro, Isaribi, Kirsch, Procy, Furlong, Victom, Kyoichi, Shoen, Toshu, Hitomi, Kouki & Sirius, Digram, Marfik, Polaris Mask and Alchiba for heroes

**Comment by InqEretaH** [comment]
Maybe make a navbox template for heroes

**Comment by InqEretaH** [comment]
also pls move images to the imgs folder and remove the test file, I forgot how to do that oops

**Comment by rongjiecomputer** [comment]
- Hero pages have been added, but the information in each page still need to be updated.
- `assets/img` has been tidied up.
- Not sure what is nabox template for heroes, maybe this: https://liveahero-wiki.github.io/heroes/ ?
