### ISSUE TITLE
Datamine and stitch character Atlas texture files

### ISSUE THREAD

**Issue by rongjie-alter** [liveahero-wiki/liveahero-wiki.github.io#20]
EDIT 2020/10/04: Owner of Housamo Wiki has provided some help in datamining and stitching character Atlas files automatically. Please pause manual stitching work until further notice.

I am currently working on bringing the character and skill info up on wiki as soon as possible, so I don't have time to work on image files yet.

I know a lot of member in the community has the expertise in stitching Atlas texture file very nicely, so I thought maybe y'all can start working on it, then when I have time to make wiki templates for images, I will have some images ready to test.

(I don't think I will ever figure out how to automate the image stitching process, so I guess we will be doing it manually for quite some time)

This issue is to coordinate those who want to help on this and share tips on how to stich texture beautifully/efficiently.

What images we needed:

- Sprites (including `skin1` and expressions) of Hero, and Sidekick
- Sprites (including `skin1` and expressions) of unreleased unit (less important for now)
- Icons for Hero and Sidekick (just need the default expression)
- Icon for status and item

Requirement:

- Keep the original file name if possible so that I can match up with the game masterdata (like the `fg_akashi_h01` prefix and `_skin1` suffix)
- Image should be in `.png` format with transparent background (but you can have `.psd` files etc as backup)
- Compress the images into a zipped folder (`.zip` or `.7z` are both acceptable)
- I think you can drag and drop the zipped folder to this Github page (though I am not sure about the attachment size limit). If it exceeds the size limit, just put in Google Drive or somewhere else first.
- You can split files into multiple batches when uploading to workaround with size limit

You can add comment on who you want to work on and/or already done to avoid duplication of effort by different people.

I will unsubscribe myself from this issue, foreseeing that this might get a lot of comments. Ping me if something needs my attention.

**Comment by skinnybear** [comment]
https://drive.google.com/file/d/1igj90505-CJxKHtPH9zxI4uYwbNm_6kH/view?usp=sharing
fg_akashi_h02_Atlas0 updated to

**Comment by primal-meridian** [comment]
[Broker.zip](https://github.com/liveahero-wiki/liveahero-wiki.github.io/files/5320209/Broker.zip)

**Comment by primal-meridian** [comment]
[Player.zip](https://github.com/liveahero-wiki/liveahero-wiki.github.io/files/5322046/Player.zip)

**Comment by primal-meridian** [comment]
[Broker Sprites.zip](https://github.com/liveahero-wiki/liveahero-wiki.github.io/files/5322118/Broker.Sprites.zip)

**Comment by skinnybear** [comment]
Akashi Tamamura (wip, awaiting for missing spirit)
    Alchiba (completed)
    Crowne Applefield (completed)
    Digram (wip)
    Furlong *
    Goro 
    Hitomi
    Huckle
    Isaribi
    Kirsch
    Kouki & Sirius
    Kyoichi
    Loren
    Marfik *
    Mokdai (completed)
    Narihito
    Player (completed)
    Polaris Mask
    Procy
    Rakta
    Ryekie (completed, awaiting to be uploaded)
    Shoen
    Sui
    Toshu
    Victom *
* partially done, please refer to the Google drive
