### ISSUE TITLE
Add some info for /gameplay/ page

### ISSUE THREAD

**Issue by rongjie-alter** [liveahero-wiki/liveahero-wiki.github.io#4]
- Read https://liveahero-wiki.github.io/contributing/ about how to contribute
- Go to https://liveahero-wiki.github.io/gameplay/
- Click any of the page
- Click Edit this page
- Add translated notes of gameplay from LAH_ENG twitter

**Comment by Afrosketches** [comment]
I'll take on adding the translated notes of gameplay to this page.

**Comment by Afrosketches** [comment]
Gameplay notes and screenshots are now live.
