### ISSUE TITLE
Datamining masterdata files

### ISSUE THREAD

**Issue by InqEretaH** [liveahero-wiki/liveahero-wiki.github.io#7]
Unlike Housamo, LAH's masterdata files are not encrypted at all and can be viewed as plain text, even on the phone. It trivializes datamining and allows wiki to have more exact data, especially about gameplay (even though said gameplay is explained a bit better this time)

Some notes:
* Masterdata files are found at *game directory/files/datas/master*. They are completely unencrypted (for now at least)
* CardMaster holds info for all the heroes of each rarity, including their skills, non-linearly-growing and rarity-dependent stats, job, affiliation office (?), illustrator and voice actor.
* SidekickMaster does the same but for sidekick cards.
* Skill linked in CardMaster are found in SkillMaster. That file lists a skill's effects, the targets (0 for self, 1 for allies and 2 for enemies) and the proc rate.
* Skill effects linked in SkillMaster are found in SkillEffectMaster. This is the most important file and basically says what all skills do. Listed there are effects, their potency and a few flags:
    * isImmediate: if true, will trigger immediately, else at the end of turn for "turn" amount of turns.
    * persistence: if true, the effect lasts forever (probably)
    * canDuplicate: probably to allow/disallow stacking of an effect
* StatusMaster so far seems to be for cosmetic purposes only as the effects themselves are described in SkillEffectMaster.

Feel free to leave your thoughts and findings.

**Comment by InqEretaH** [comment]
Random find: HealthDamage effect increases damage by the parameter at max hp and by 2x the parameter at 0 hp

**Comment by InqEretaH** [comment]
effectTarget map:
0 - self
1 - target ally
2 - target enemy
3 - all allies
4 - all enemies
5 - ??? (used in an event skill)

**Comment by InqEretaH** [comment]
timing map:
0 - base skill
1 - when appearing
2 - action start
3 - action end
4, 5 ,6 - ?
7 - when attacking
8 - when taking damage
9 - ?
10 - permanent effect
11 - ??? (i really don't know what that is)

**Comment by InqEretaH** [comment]
effect map:
Damage - Deal (value)% of damage
ChangeHP - Decrease/Increase HP by (-value)% to (target) (yes it's reversed)
MultipleAttack - ATK Up/Down by (value/100)x to (target)
MultipleBaseView - Base View Up/Down by (value/100)x to (target)
ChangeView - Add (value) views
MultipleDefence - DEF Up/Down by (value/100)x to (target)
ChangeAgi - SPD Up/Down by (value) to (target)
RemoveBuff - Remove (value) buffs from (target)
ComboPlus - Gain (value) combos to (target)
ChangeSkillProve - Proc rate Up/Down by (value) for (target)
MoreTurn - Perform (value) more action(s)
Heal - Heal (target) for (value)% of own(?) ATK value
NeedViewChange - Skill View cost Up/Down by (value/100)x for (target)
Cure - Remove (value) debuff(s) from (target)
RegistDebuff - (value)% chance to resist a debuff for (target)
Provocation - Give (target) Taunt. Opponents can target only (target)
HealthDamage - Deal (value)% -> (2*value)% as HP goes from Max to 0
DeleteTurn - Skip (value) enemy action(s)
Silence - (target) cannot use view-costing skills
ComboDamage - Deal (value)% of damage and (combpMult)% extra for each combo
ElementPenetrateDamage - ATK Up/Down to (target) by (value/100)x against advantageous elements
Wait - Make (target) go last
ComboMultipleAttack - ATK Up by (value)% to (target) for each combo
SpdDeferenceMultipleAttack - ATK Up by (spdMult)% to (target) for each point in speed difference (???)
Penetration - Make (target) ignore Taunt
AllAttack - View-costing skills for (target) now target all allies/enemies
MultipleHP - HP Up by (value/100)x to (target)
StatusNumberMultipleAttack - ATK Up by (value)% to (target) for each (isGoodStatus ? buff : debuff)
NeedViewValueChange - Change skill view cost by (value) for (target)
IgnoreElement - Make (target) ignore element advantages
NowViewDamage - Deal Damage based on views (needs more research on how it works, encountered in Polaris 3rd skill)
SpdDeferenceDamage - Deal Damage based on speed advantage (needs more research, encountered in Ryekie's 3rd skill)
StatusNumDamage - Deal (value)% of damage and (statusMult)% extra for each opponent's (isGoodStatus ? buff : debuff)
SalesBonusCheat - Ignore business bonus conditions (?)
IncreaseLAH - Gain (value)% extra gold
IncreaseExp - Gain (value)% extra XP
Aggregation - Aggregate damage (?)

Still a few question marks here and there, feel free to fill the blanks

**Comment by rongjie-alter** [comment]
there is this skill effect without an explanation yet (akashi's) `[{"class":"ChangeHp","parameter":{"value":10}}`

**Comment by InqEretaH** [comment]
Right, I capitalized it incorrectly. It's the 2nd entry in the map I posted above

**Comment by InqEretaH** [comment]
Edited capitalization for ChangeHp and MultipleHp

**Comment by InqEretaH** [comment]
trigger map (conditions for the skill to trigger, can be put in parenthesis before the skill description):
MinComboTrigger - (value)+ combos
MinHPTrigger - (value)+% HP
MaxHPTrigger - (value)-% HP

**Comment by rongjie-alter** [comment]
Oh god, this is not implementable with Jekyll/Liquid template: it is impossible to parse a string field into object without a plugin...

**Comment by rongjie-alter** [comment]
you know what, this part will be implemented in client side js (I almost forgot about this)

**Comment by InqEretaH** [comment]
Some things I noticed right away:
There needs to be some distinction between hero cards and sidekicks
Sidekick parts still show hero sprites
Sidekick rarities in the stat table are all listed as the same

**Comment by InqEretaH** [comment]
Also stats for heroes can be trimmed as I don't think 3* heroes can reach over lv 30, 4* heroes over lv 40, etc

**Comment by Kapoisu** [comment]
> 
> 
> timing map:
> 0 - base skill
> 1 - when appearing
> 2 - action start
> 3 - action end
> 4, 5 ,6 - ? (no skills with such timing)
> 7 - when attacking
> 8 - when taking damage
> 9 - ? (no skills with such timing)
> 10 - permanent effect
> 11 - ??? (i really don't know what that is)

From my understanding, 1 is for characters with clothing undamaged (above 50% of health); 11 is for the opposite.

**Comment by Mjmithu** [comment]
> ### [_****_](https://github.com/liveahero-wiki/liveahero-wiki.github.io.git)
