### ISSUE TITLE
Displaying skill info of hero and sidekick with data mining

### ISSUE THREAD

**Issue by rongjie-alter** [liveahero-wiki/liveahero-wiki.github.io#8]
Since masterdata are in nice JSON format, we can have some nice Jekyll/Liquid templating to automate a lot of things

Current implementation plan:

- [x] Display base card info (base HP, ATK etc)
- [x] Display skills in Japanese form
- [x] Display Japanese card bio
- [ ] Parse and display skills in generated English form

Hero/sidekick sprites are de-prioritized for now

**Comment by InqEretaH** [comment]
Calculating maxed card info isn't really necessary as they're already done in the masterdata files themselves. The values given there are also arbitrary and would be different to calculate normally.
